### ISSUE TITLE
[ENH] Checklist for deprecation in V0.8.0

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1238]
### Describe the feature or idea you want to propose

todo list for deprecation prior to 0.8.0

### Describe your proposed solution

list

- [x] remove the support_probabilities parameter in WEASELV2. @patrickzib 
- [x] remove plot_series from utils/plotting.py
- [x] remove remove 'save_transformed_data' and 'transformed_data_' in BaseIntervalForest, FreshPrince, STC, Arsenal see #1332 1332
- [x] remove the save_train_predictions parameter in BOSSEnsemble, CBOSS, TemporalDictionaryEnsemble, OrdinalTDE #1333
- [x] remove MatrixProfileClassifier #1333
- [x] refactor uses of get_examples, leave version in datatypes just for use in datatypes.
- [x] swap the position of the classifier and transformers argument in ClassifierPipeline
- [x] EAgglo class in annotation #1306 
- [x] HMM class in annotation #1306 
- [x] remove overloaded operators in BaseClassifier #1265 
- [x] remove overloaded operators in ClassifierPipeline #1265 
- [x] remove BaseForecastingErrorMetric and all subclasses  #1261 
- [x] remove Filter from transformations #1306 
- [x] remove Hidalgo in transformations #1306 
- [x] remove MatrixProfileTransformer from transformations #1306 
- [x] remove mlflow_aeon.py #1285 

going to roll this over
- [x] refactor datatypes._adaptors to utils.conversion

**Comment by TonyBagnall** [comment]
done
