### ISSUE TITLE
[ENH] Checklist for deprecation in V0.9.0

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1239]
### Describe the feature or idea you want to propose

Would be good to actively update this list rather than do it in batch mode

### Describe your proposed solution
- [x] Remove utils.validation.panel.py #1464
- [x] Remove overloaded multiplication in BaseRegressor #1464
- [x] refactor datatypes._adaptors to utils.conversion. Reversed deprecation, #1489
- [x] remove stratified_resample from utils.sampling.py #1464
- [x] remove classification.distance_based.ShapeDTW https://github.com/aeon-toolkit/aeon/pull/1470
- [x] move channel selection to its own package https://github.com/aeon-toolkit/aeon/pull/1466
- [x] remove seasonality.py from utils #1464 
- [x] Regressor pipeline init function #1488 
- [x] Remove SklearnRegressorPipeline #1488
