### ISSUE TITLE
`aeon` v1.0.0 Checklist

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1518]
### Describe the issue

A checklist of large-scale changes to be made for an eventual version v1.0.0

- [ ] Deprecate `BaseTransformer` and remove experimental tag from `BaseSeriesTransformer`
- [ ] Replace `forecasting` and `BaseForecaster` with simplified and more maintainable version
- [ ] Merge `BaseEstimator` and `BaseObject` and consider deprecation for a few of the currently available methods
- [ ] Replace current fixture/scenario based testing with a simplified testing suite. Remove experimental tag for `testing`
- [ ] Consider removing experimental tag for other modules

**Comment by TonyBagnall** [comment]
we can do these things before going to 1.0.0. Personally I think 1.0.0 should come at the end of the grant

**Comment by MatthewMiddlehurst** [comment]
I think deprecating a whole module is a big enough of a change to warrant it. I don't know what would be if not. I think it's best just to get these big ones out at the same time.

**Comment by chrisholder** [comment]
I think we should add I better directory structure to the distance module. Currently it's just one flat directory. 

Currently I was thinking we should have something like:

-> Elastic
-> Cross-Correlation
-> Lp (or a better name to describe non time series distances like Euclidean)
-> then either one or multiple directories for distances like dtt_sfa, sax and mpdist which I don't know how/where they would fall into

**Comment by TonyBagnall** [comment]
not sure what happened to forecasting here, seems to have been removed. I put it back
