### ISSUE TITLE
[ENH] Checklist for deprecation in V0.11.0

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#1611]
- [x] Remove SplitTimeSeries #1613 
- [x] Remove PandasAdaptor #1614
- [x] Move compose to _legacy #1679 
- [x] Remove `BaseDeepNetwork`
- [x] Remove MiniRocket multivariate #1708 
- [x] Remove MultiRocketMultivariate
- [x] Move MrSQM to dictionary_based
- [x] Delete or movbe to _legacy all BaseTransformers 
- [x] Remove BKFilter #1788
