### ISSUE TITLE
[ENH] KDD 2024 tutorial code checklist

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1654]
Some potential issues which need work for the upcoming KDD tutorial:

- [x] Add tests to ensure distances work with `scikit-learn` estimators/interface @dguijo  => #1838 
- [x] Revisit pipeline testing for both classification and regression, ensure it works for both learning tasks with collection and series transformers @MatthewMiddlehurst => #1853
- [x] Finish off estimator specific visualisation techniques 
     - [x] Temporal importance curves for interval classifiers @MatthewMiddlehurst 
     - [x] Most informative shapelets for STC and RDST @baraline => #1824 
- [ ] Add some general visualisation methods for evaluating feature importance
- [ ] Add composable estimators for tuning classifiers and regressors
- [x] Add composable estimators for creating ensembles of classifiers and regressors @MatthewMiddlehurst =>#1853
- [x] Clean up `networks` for use in the demonstration (i.e. proper testing and remove deprecated base) @hadifawaz1999  => #1817 
- [ ] Add contents to `benchmarking` for the EEG example
