### ISSUE TITLE
[ENH] ECML-PKDD 2024 tutorial checklist

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1655]
See also: #1654 

- [x] PyOD adapter for anomaly detection #1586 
- [x] Performance metrics for anomaly detection (PR-AUC or PR-VUS) #1938
- [ ] Examples notebook for anomaly detection
- [x] Add STOMP matrix profile for series search #2010 (STUMP is equivalent to the naive version)
