### ISSUE TITLE
[ENH] Excluded estimators and tests

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon#2230]
### Describe the feature or idea you want to propose

the new testing set up has identified a lot of new previously undisclosed test fails, resulting in many exclusions. These are listed in testing_config, and listed below. It would be good to have issues with each exclusion, to help find solutions, see https://github.com/aeon-toolkit/aeon/issues/2071 for a starting point

### Describe your proposed solution

Excluded estimators

- [x] SeriesSearch
- [x] QuerySearch
- [x] ClearSkyTransformer
- [x] RandomDilatedShapeletTransform
- [x] RDSTRegressor
- [x] RISTRegressor

excluded tests (excluded for unknown reasons)

- [x] "LearningShapeletClassifier": ["check_fit_deterministic"], # has a keras fail, unknown reason, see #1387
- [x] "TapNetClassifier": ["check_classifier_random_state_deep_learning"],  # does not fit structure for test, needs investigation
- [x] "TapNetRegressor": ["check_regressor_random_state_deep_learning"],
- [ ] "SASTClassifier": ["check_fit_deterministic"],
- [ ] "RSASTClassifier": ["check_fit_deterministic"],
- [ ] "SAST": ["check_fit_deterministic"],
- [ ] "RSAST": ["check_fit_deterministic"],
- [x] "AEFCNClusterer": ["check_fit_updates_state"], Fixed in #2309 
- [x] "AEResNetClusterer": ["check_fit_updates_state"], Fixed in #2309 
- [ ] "SFA": ["check_persistence_via_pickle", "check_fit_deterministic"],
- [ ] "CollectionId": ["check_transform_inverse_transform_equivalent"],
- [ ] "ScaledLogitSeriesTransformer": ["check_transform_inverse_transform_equivalent"],
- [ ] "MockMultivariateSeriesTransformer": [
        "check_transform_inverse_transform_equivalent"
    ],
    # missed in legacy testing, changes state in predict/transform
- [ ] "FLUSSSegmenter": ["check_non_state_changing_method"],
- [ ]  "InformationGainSegmenter": ["check_non_state_changing_method"],
- [ ] "GreedyGaussianSegmenter": ["check_non_state_changing_method"],
- [ ] "ClaSPSegmenter": ["check_non_state_changing_method"],
- [ ] "HMMSegmenter": ["check_non_state_changing_method"],
- [ ] "BinSegSegmenter": ["check_non_state_changing_method"],
- [ ] "QUANTTransformer": ["check_non_state_changing_method"],
- [ ] "MatrixProfileSeriesTransformer": ["check_non_state_changing_method"],
- [ ] "PLASeriesTransformer": ["check_non_state_changing_method"],
- [ ] "AutoCorrelationSeriesTransformer": ["check_non_state_changing_method"],
- [ ] "SIVSeriesTransformer": ["check_non_state_changing_method"],

**Comment by TonyBagnall** [comment]
I'm closing this in preference to test specific issues, i.e. estimators that fail given tests, as its easier to diagnose
