### ISSUE TITLE
[ENH] Refactoring Piecewise Transformation aka PAA and SAX

### ISSUE THREAD

**Issue by hadifawaz1999** [aeon-toolkit/aeon#434]
### Describe the feature or idea you want to propose

PAA should:

- [x] Use numpy internally #269 
- [x] Be refactored to use numba -- No need its already vectorized see #489 
- [x] add an inverse function to approximate TS #489
- [ ] Should be put in collection, not collection/dictionary_based
- [x] Refactor tests to use numpy #199
- [x] Refactor tests to new implementation usage #489

SAX should:

- [x] Use numpy internally #417 
- [x] Be refactored to use numba #417 
- [x] Use scipy to calculate breakpoints automatically #417 
- [x] add an inverse function to approximate  #417 
- [x] Refactor tests to use numpy #417 
- [x]  Refactor tests to new implementation usage #417 

- Add everything to codeowners after collections/panel thing is sorted out

### Describe your proposed solution

Doing it myself, once SAX is done, PAA should be addressed. A time comparison should be done after all of this is done.

**Comment by MatthewMiddlehurst** [comment]
Is this finished or are there other things planned?

**Comment by hadifawaz1999** [comment]
yup its finished @MatthewMiddlehurst thanks for the reminder
